# Generated by Django 3.2.8 on 2022-02-26 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('listingid', models.AutoField(primary_key=True, serialize=False)),
                ('listingname', models.CharField(max_length=100)),
                ('baseprice', models.DecimalField(decimal_places=5, max_digits=100)),
                ('imageurl', models.URLField()),
                ('category', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('OPEN', 'Lisitng is Open'), ('CLOSED', 'Listing is Closed')], default='OPEN', max_length=7)),
                ('listingwinner', models.CharField(max_length=100)),
                ('listingsaleprice', models.DecimalField(decimal_places=5, max_digits=100)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('watchid', models.AutoField(primary_key=True, serialize=False)),
                ('itemid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listing')),
                ('ownerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('commentry', models.CharField(max_length=500)),
                ('commentator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('itemid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listing')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('bidid', models.AutoField(primary_key=True, serialize=False)),
                ('latestbid', models.DecimalField(decimal_places=5, max_digits=100)),
                ('itemid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listing')),
            ],
        ),
    ]
