# Generated by Django 3.2.8 on 2022-02-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comment_listing_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listingsaleprice',
            field=models.DecimalField(decimal_places=5, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listingwinner',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
