# Generated by Django 3.2.8 on 2022-02-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20220227_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listingsaleprice',
            field=models.DecimalField(blank=True, decimal_places=5, default=None, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listingwinner',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
