# Generated by Django 3.2.8 on 2022-03-07 04:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20220227_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listingdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
