# Generated by Django 3.2.8 on 2022-03-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_bid_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='latestbid',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
