# Generated by Django 3.2.8 on 2022-03-09 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_watchlist_ownerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='itemid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listing', unique=True),
        ),
    ]
