# Generated by Django 3.2.8 on 2022-03-10 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_watchlist_ownerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='itemid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemcomments', to='auctions.listing'),
        ),
    ]
