# Generated by Django 3.2.8 on 2022-03-11 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_comment_itemid'),
    ]

    operations = [
        migrations.CreateModel(
            name='WonBid',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('winnerbid', models.DecimalField(decimal_places=2, max_digits=100)),
                ('itemid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listing')),
                ('winnerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
