# Generated by Django 3.2.8 on 2022-03-11 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_wonbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='itemid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listing'),
        ),
    ]
